# Generated by Django 4.2.11 on 2024-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_lesson_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='materials/courses/previews', verbose_name='логотип'),
        ),
    ]
