# Generated by Django 4.2.11 on 2024-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_remove_lesson_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/lessons/', verbose_name='логотип'),
        ),
    ]
